EmployeesSysytem/Models/LeaveApplication.cs
using System.ComponentModel.DataAnnotations;

namespace EmployeesSysytem.Models
{
    public class LeaveApplication : ApprovalActivity
    {
        public int Id { get; set; }
        [Display(Name ="Employee")]
        public int EmployeeId { get; set; }
        public Employee? Employee { get; set; }
        [Display(Name = "Days")]
        public int NoOfDays { get; set; }
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }
        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }
        [Display(Name ="Duration")]
        public int DurationId { get; set; }
        public SystemCodeDetail? Duration { get; set; }
        [Display(Name = "Leave Type")]
        public int LeaveTypeId { get; set; }
        public LeaveType? LeaveType { get; set; }
        public string? Attachment { get; set; }
        [Display(Name = "Notes")]
        public string? Description { get; set; }
        [Display(Name = "Status")]
        public LeaveStatus LeaveStatus { get; set; } = LeaveStatus.AwaitingApprove;
        public bool IsChanged { get; set; } = false;
    }

    public enum LeaveStatus
    {
        AwaitingApprove,
        Pending,
        Apprvoed,
        Rejected
    }

}

EmployeesSysytem/Controllers/LeaveApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeesSysytem.Data;
using EmployeesSysytem.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Hosting;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.Identity;
using Microsoft.CodeAnalysis.Elfie.Model.Strings;
using EmployeesSysytem.Models.ViewModels;

namespace EmployeesSysytem.Controllers
{
    public class LeaveApplicationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<ApplicationUser> _userManager;

        public LeaveApplicationsController(ApplicationDbContext context, IWebHostEnvironment environment, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _environment = environment;
            _userManager = userManager;
        }

        // GET: LeaveApplications
        public async Task<IActionResult> Index()
        {
            var applicationsQuery = _context.LeaveApplications!.Include(l => l.Duration)
            .Include(l => l.Employee)
            .Include(l => l.LeaveType)
            .AsQueryable();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employee = _context.Employees!.FirstOrDefault(x => x.UserId == userId);
            if (userId != null)
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    var role = (await GetRole()).ToString();
                    if (role != null)
                    {
                        if (role.Contains("manager"))
                        {
                            applicationsQuery = applicationsQuery.
                                Where(d => d.Employee!.DepartmentId == employee!.DepartmentId);

                        }
                        else if (role.Contains("boss") || role.Contains("admin") || role.Contains("hr"))
                        {

                        }
                        else
                        {
                            applicationsQuery = applicationsQuery.Where(x => x.Employee!.UserId == userId);
                        }

                    }
                }
            }
            var applications = await applicationsQuery.ToListAsync();
            return View(applications);
        }

        // GET: LeaveApplications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveApplication = await _context.LeaveApplications!
                .Include(l => l.Duration)
                .Include(l => l.Employee)
                .Include(l => l.LeaveType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leaveApplication == null)
            {
                return NotFound();
            }
            var userId = GetUserId();
            var role = (await GetRole()).ToString();

            if (role != null)
            {
                ViewBag.isManager = role.Contains("manager");
                ViewBag.isBoss = role.Contains("boss");
                ViewBag.isAdmin = role.Contains("admin");
                ViewBag.isHR = role.Contains("hr");
                ViewBag.isApplicationer = leaveApplication.Employee != null && leaveApplication.Employee.UserId == userId;
            }
            else
            {
                ViewBag.isManager = false;
                ViewBag.isBoss = false;
                ViewBag.isAdmin = false;
                ViewBag.isHR = false;
                ViewBag.isApplicationer = false;
            }
            ViewBag.leavedays = leaveApplication.NoOfDays;
            return View(leaveApplication);
        }

        public async Task<IActionResult> DownloadFile(int id)
        {
            var leaveApplication = await _context.LeaveApplications!.FindAsync(id);
            if (leaveApplication == null || string.IsNullOrEmpty(leaveApplication.Attachment))
            {
                return NotFound();
            }
            var pathDir = Path.Combine(_environment.WebRootPath, "LeaveApplications/Attachments");
            var filePath = Path.Combine(pathDir, leaveApplication.Attachment);
            if (!System.IO.File.Exists(filePath))
            {
                return NotFound();
            }
            byte[] fileBytes = await System.IO.File.ReadAllBytesAsync(filePath);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, leaveApplication.Attachment);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateStatus(int? id, string status)
        {
            var userId = GetUserId();
            var user = _context.ApplicationUsers.FirstOrDefault(x => x.Id == userId);
            var leaveApplication = await _context.LeaveApplications!.Include(x => x.Employee).FirstOrDefaultAsync(y => y.Id == id);
            var employee = leaveApplication?.Employee;
            if (id == null || _context.LeaveApplications == null)
            {
                return NotFound();
            }
            if (status == "Apprvoed")
            {
                leaveApplication!.LeaveStatus = LeaveStatus.Apprvoed;
                leaveApplication!.ApprovalOn = DateTime.Now;
                leaveApplication.ApprovalById = user?.FullName ?? null;
                var leaveAdjust = new LeaveAdjustmentEntry()
                {
                    EmployeeId = employee!.Id,
                    NoOfDays = leaveApplication?.NoOfDays ?? 0,
                    LeaveAdjustmentDate = DateTime.Now,
                    LeaveStartDate = leaveApplication!.StartDate,
                    LeaveEndDate = leaveApplication!.EndDate
                };
                if (leaveApplication.LeaveTypeId == 1)
                {
                    employee.TotalLeaveDays = employee.TotalLeaveDays + leaveApplication.NoOfDays;
                    employee.LeaveOutStandingBalance = employee.AllocatedLeaveDays - employee.TotalLeaveDays;
                }
                leaveApplication.IsChanged = true;
                _context.LeaveApplications.Update(leaveApplication!);
                _context.Employees!.Update(employee);
                _context.LeaveAdjustmentEntries!.Add(leaveAdjust);
                await _context.SaveChangesAsync(userId);
                return RedirectToAction("Index");

            }
            else if (status == "Pending")
            {
                leaveApplication!.LeaveStatus = LeaveStatus.Pending;
            }
            else if (status == "Rejected")
            {
                leaveApplication!.LeaveStatus = LeaveStatus.Rejected;
                leaveApplication.IsChanged = true;
            }
            _context.LeaveApplications.Update(leaveApplication!);
            await _context.SaveChangesAsync(userId);
            return RedirectToAction(nameof(Details), new { id = leaveApplication!.Id });
        }


        // GET: LeaveApplications/Create
        public IActionResult Create()
        {
            ViewData["DurationId"] = new SelectList(_context.SystemCodeDetails!.Include(x => x.SystemCode).Where(y => y.SystemCode!.Description == "Duration"), "Id", "Description");
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "FullName");
            ViewData["LeaveTypeId"] = new SelectList(_context.LeaveTypes, "Id", "Name");
            return View();
        }

        // POST: LeaveApplications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeaveApplication leaveApplication, IFormFile leaveAttachment)
        {
            ViewData["DurationId"] = new SelectList(_context.SystemCodeDetails!.Include(x => x.SystemCode).Where(y => y.SystemCode!.Name == "Duration"), "Id", "Description");
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "FullName", leaveApplication.EmployeeId);
            ViewData["LeaveTypeId"] = new SelectList(_context.LeaveTypes, "Id", "Name", leaveApplication.LeaveTypeId);
            try
            {
                if (leaveAttachment != null && leaveAttachment.Length > 0)
                {
                    var fileName = DateTime.Now.ToString("yyyyMMdd_HHmmss") + "_" + leaveAttachment.FileName;
                    var uploadDir = Path.Combine(_environment.WebRootPath, "LeaveApplications/Attachments");
                    var filePath = Path.Combine(uploadDir, fileName);
                    FileStream fs = new FileStream(filePath, FileMode.Create);
                    await leaveAttachment.CopyToAsync(fs);
                    fs.Close();
                    leaveApplication.Attachment = fileName;
                }
                var userId = User.FindFirstValue(ClaimTypes.Name);
                leaveApplication.CreatedOn = DateTime.Now;
                leaveApplication.CreatedById = "Ethan Wang";
                _context.Add(leaveApplication);
                await _context.SaveChangesAsync(userId);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View(leaveApplication);

            }
        }

        // GET: LeaveApplications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

EmployeesSysytem/Views/LeaveApplications/Create.cshtml
@model EmployeesSysytem.Models.LeaveApplication

@{
    ViewData["Title"] = "Create";
}

<div class="card">
    <div class="card-header"><h3>Add New Leave</h3></div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EmployeeId" class="control-label"></label>
                                <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="NoOfDays" class="control-label"></label>
                                <input asp-for="NoOfDays" class="form-control" />
                                <span asp-validation-for="NoOfDays" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DurationId" class="control-label"></label>
                                <select asp-for="DurationId" class="form-control" asp-items="ViewBag.DurationId"></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="LeaveTypeId" class="control-label"></label>
                                <select asp-for="LeaveTypeId" class="form-control" asp-items="ViewBag.LeaveTypeId"></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Attachment" class="control-label"></label>
                                <input  class="form-control" type="file" accept=".png,.jpg,.pdf" id="photo" name="leaveAttachment" />
                                <span asp-validation-for="Attachment" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control" ></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group mx-2">
                            <input type="submit" value="Save Leave" class="btn btn-primary" />
                        </div>
                        <div class="form-group mx-2">
                            <a asp-action="Index" class="btn btn-warning">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

EmployeesSysytem/Views/LeaveApplications/Delete.cshtml
@model EmployeesSysytem.Models.LeaveApplication

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LeaveApplication</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee!.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoOfDays)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration!.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveType.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Attachment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Attachment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalById)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApprovalById)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApprovalOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedById)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedById)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedById)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EmployeesSysytem/Views/LeaveApplications/Details.cshtml
@model EmployeesSysytem.Models.LeaveApplication

@{
    ViewData["Title"] = "Details";
    bool isManager = ViewBag.isManager;
    bool isBoss = ViewBag.isBoss;
    bool isAdmin = ViewBag.isAdmin;
    bool isHR = ViewBag.isHR;
    bool isApplicationer = ViewBag.isApplicationer;
    decimal leavDays = ViewBag.leavedays;
}

<h1>Details</h1>

<div>
    <h4>LeaveApplication</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee!.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfDays)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NoOfDays)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Duration!.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveType!.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Attachment)
        </dt>
        <dd class="col-sm-10">
            @if (!string.IsNullOrEmpty(Model.Attachment))
            {
                <a asp-action="DownloadFile" asp-controller="LeaveApplications"
                   asp-route-id="@Model.Id"><i class="fa-solid fa-cloud-arrow-down mx-1"></i>Download Attachment</a>
            }
            else
            {
                @Html.DisplayFor(model => model.Attachment)
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalById)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalById)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedById)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedById)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedById)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>
</div>
<div class="row mt-3">
    @if ((isAdmin || isManager || isBoss) && !isApplicationer)
    {
        @if (leavDays <= 5 || !isManager)
        {
            @if (Model.LeaveStatus != LeaveStatus.Apprvoed)
            {
                <form style="display:inline" method="post" asp-controller="LeaveApplications" asp-action="UpdateStatus" class="mx-3">
                    <input type="hidden" name="id" value="@Model.Id" />
                    <input type="hidden" name="status" value="Apprvoed" />
                    <button type="submit" class="btn btn-primary">Approved</button>
                </form>
            }    
        }
        @if (Model.LeaveStatus != LeaveStatus.Pending)
        {
            <form style="display:inline" method="post" asp-controller="LeaveApplications" asp-action="UpdateStatus" class="mx-3">
                <input type="hidden" name="id" value="@Model.Id" />
                <input type="hidden" name="status" value="Pending" />
                <button type="submit" class="btn btn-warning">Pending</button>
            </form>
        }
        @if (Model.LeaveStatus != LeaveStatus.Rejected)
        {
            <form style="display:inline" method="post" asp-controller="LeaveApplications" asp-action="UpdateStatus" class="mx-3">
                <input type="hidden" name="id" value="@Model.Id" />
                <input type="hidden" name="status" value="Rejected" />
                <button type="submit" class="btn btn-danger">Rejected</button>
            </form>
        }
    }
    <div>
        @if (isApplicationer && !isBoss)
        {
            <a asp-action="Edit" asp-route-id="@Model.Id" class="mx-4 btn btn-success">Edit</a>
        }

        <a asp-action="Index" class="mx-2 btn btn-info">Back to List</a>
    </div>
</div>

EmployeesSysytem/Views/LeaveApplications/Edit.cshtml
@model EmployeesSysytem.Models.LeaveApplication

@{
    ViewData["Title"] = "Edit";
}

<div class="card">
    <div class="card-header"><h3>Edit Leave</h3></div>
    <div class="card-body">
        <div class="row">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="EmployeeId" class="control-label"></label>
                            <select asp-for="EmployeeId" class="form-control" asp-items="ViewBag.EmployeeId"></select>
                            <span asp-validation-for="EmployeeId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="NoOfDays" class="control-label"></label>
                            <input asp-for="NoOfDays" class="form-control" />
                            <span asp-validation-for="NoOfDays" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="StartDate" class="control-label"></label>
                            <input asp-for="StartDate" class="form-control" />
                            <span asp-validation-for="StartDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="EndDate" class="control-label"></label>
                            <input asp-for="EndDate" class="form-control" />
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="DurationId" class="control-label"></label>
                            <select asp-for="DurationId" class="form-control" asp-items="ViewBag.DurationId"></select>
                            <span asp-validation-for="DurationId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="LeaveTypeId" class="control-label"></label>
                            <select asp-for="LeaveTypeId" class="form-control" asp-items="ViewBag.LeaveTypeId"></select>
                            <span asp-validation-for="LeaveTypeId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Attachment" class="control-label"></label>
                            <input class="form-control" type="file" accept=".png,.jpg,.pdf" id="photo" name="leaveAttachment" />
                            <span asp-validation-for="Attachment" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" class="form-control" ></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group mx-2">
                        <input type="submit" value="Edit Leave" class="btn btn-primary" />
                    </div>
                    <div class="form-group mx-2">
                        <a asp-action="Index" class="btn btn-warning">Back to List</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}